- name: Setup
  hosts: all
  become: yes
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nodejs
    - geerlingguy.docker