name: Development

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
        env:
          CI: true

  deploy:
    name: CD part
    runs-on: ubuntu-latest

    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAUJBBT5OBMGRTGQUJ'
          aws-secret-access-key: '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'
          aws-region: eu-central-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Push image to Amazon ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ride-core
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "REJfSE9TVD1zcWwxCkRCX05BTUU9YnNlbHNjcmlwdApEQl9VU0VSTkFNRT1TQQpEQl9QQVNTV09SRD1wMXJybUppbQpEQl9QT1JUPTE0MzMKREJfQ0xJRU5UPW1zc3FsCgojIENsaWVudCBkYXRhYmFzZSBuYW1lcwpCU0VMU0NSSVBUX0RCX0NPTk49bXNzcWw6Ly9TQTpwMXJybUppbUBzcWwxOjE0MzMvYnNlbHNjcmlwdApFTEFMX0RCX0NPTk49bXNzcWw6Ly9TQTpwMXJybUppbUBzcWwxOjE0MzMvZWxhbApTSEVCQV9EQl9DT05OPW1zc3FsOi8vU0E6cDFycm1KaW1Ac3FsMToxNDMzL3NoZWJhCklOVEVMX0RCX0NPTk49bXNzcWw6Ly9TQTpwMXJybUppbUBzcWwxOjE0MzMvaW50ZWwKQ0VSQUdPTl9EQl9DT05OPW1zc3FsOi8vU0E6cDFycm1KaW1Ac3FsMToxNDMzL2NlcmFnb24KCiMgTm8gY29sb3IgZm9yIHRoZSBjb25zb2xlIG91dHB1dCBsb2dzCiNOT19DT0xPUj0x" | base64 -d > env.txt
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#   deploy:
#     needs: [test]
#     runs-on: ubuntu-latest

#     steps:
#     - name: SSH and deploy node app
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_KEY }}
#         port: ${{ secrets.SSH_PORT }}
#         script: |
#           cd ~/node-github-demo
#           git pull origin master
#           npm install --production
#           pm2 restart node-app
